CREATE OR REPLACE FUNCTION CALC_INST_AMNT
RETURN NUMBER
IS 
DECLARE
V_INST_AMNT             NUMBER(8,2);
BEGIN


V_INST_AMNT := ROUND((V_FEES/C_INST_NO.PAYMENTS_INSTALLMENTS_NO)- COALESCE (V_DEPOSIT / C_INST_NO.PAYMENTS_INSTALLMENTS_NO ,0), 1);

RETURN V_INST_AMNT;
END;