SET SERVEROUTPUT ON;

--CREATE SEQUENCE INSTALLID_SEQ4 MINVALUE 1 CACHE 20 NOCYCLE;

DECLARE
 V_CONTRACT_ID      CONTRACTS.CONTRACT_ID%TYPE;
 V_ST_DATE                CONTRACTS.CONTRACT_START_DATE%TYPE;
 V_PAYMENT_TYPE     CONTRACTS.CONTRACT_PAYMENT_TYPE%TYPE;
 --V_FIRSTYEAR            NUMBER;
 V_ST_DATE_NEW              CONTRACTS.CONTRACT_START_DATE%TYPE;
 
V_INST_AMNT             NUMBER(8,2);
V_FEES   CONTRACTS.CONTRACT_DEPOSIT_FEES%TYPE;
V_DEPOSIT      CONTRACTS.CONTRACT_DEPOSIT_FEES%TYPE;
CURSOR CURSOR_CNTRCTID IS
SELECT CONTRACT_ID FROM CONTRACTS;


CURSOR CURSOR_CNTRCT_ST_DATE IS
SELECT CONTRACT_START_DATE FROM CONTRACTS;

CURSOR CURSOR_CNTRCT_END_DATE IS
SELECT CONTRACT_END_DATE FROM CONTRACTS;

CURSOR CURSOR_INST_NO IS
SELECT PAYMENTS_INSTALLMENTS_NO FROM CONTRACTS;

CURSOR CURSOR_FEES IS
SELECT CONTRACT_TOTAL_FEES FROM CONTRACTS;

CURSOR CURSOR_DEPOSIT IS
SELECT CONTRACT_DEPOSIT_FEES FROM CONTRACTS;

CURSOR CURSOR_PAYMNT_TYPE IS
SELECT CONTRACT_PAYMENT_TYPE FROM CONTRACTS;
 
BEGIN
        OPEN  CURSOR_CNTRCTID;
        OPEN  CURSOR_CNTRCT_ST_DATE;
        OPEN CURSOR_CNTRCT_END_DATE;
     --   OPEN  CURSOR_INST_NO;
        OPEN  CURSOR_FEES;
        OPEN CURSOR_DEPOSIT;
        OPEN  CURSOR_PAYMNT_TYPE;
         
        FOR C_INST_NO IN  CURSOR_INST_NO
         LOOP
            FETCH CURSOR_CNTRCTID INTO V_CONTRACT_ID;
            FETCH CURSOR_CNTRCT_ST_DATE INTO V_ST_DATE;
            FETCH  CURSOR_PAYMNT_TYPE INTO V_PAYMENT_TYPE;
            FETCH  CURSOR_FEES INTO V_FEES;
            FETCH CURSOR_DEPOSIT INTO V_DEPOSIT;
           V_ST_DATE_NEW := V_ST_DATE;
           FOR i IN 1 .. C_INST_NO.PAYMENTS_INSTALLMENTS_NO
            LOOP 
                    DBMS_OUTPUT.PUT_LINE ( V_CONTRACT_ID)  ;
                    DBMS_OUTPUT.PUT_LINE (  C_INST_NO.PAYMENTS_INSTALLMENTS_NO);
                    DBMS_OUTPUT.PUT_LINE( V_ST_DATE_NEW );
                    
                    V_INST_AMNT :=  CALC_INST_AMNT(V_FEES    ,C_INST_NO.PAYMENTS_INSTALLMENTS_NO   , V_DEPOSIT    );
                    
                    --inserrt procedure
                    
                        INSERT INTO installments_paid (INSTALLMENT_ID,             CONTRACT_ID                 , INSTALLMENT_DATE, INSTALLMENT_AMOUNT, PAID)
                                                    VALUES( INSTALLID_SEQ4.NEXTVAL,  V_CONTRACT_ID,           V_ST_DATE_NEW,      V_INST_AMNT                , 0);

                     
                    V_ST_DATE_NEW := CALC_DATE(V_ST_DATE_NEW);
                                                                                                      
 
         END LOOP;
            END LOOP;
        
       
        
        CLOSE  CURSOR_CNTRCTID;
        CLOSE  CURSOR_CNTRCT_ST_DATE;
        CLOSE CURSOR_CNTRCT_END_DATE;
       -- CLOSE CURSOR_INST_NO;
        CLOSE CURSOR_FEES;
        CLOSE CURSOR_DEPOSIT;
        CLOSE  CURSOR_PAYMNT_TYPE;
END;